### ISSUE TITLE
Use YAML list for kafka brokers

### ISSUE THREAD

**Issue by aruizeac** [alexandria-oss/core#1]
## Problem
Currently, we are using a set of objects as kafka broker list, that brings a lot of complex handling if multiple kafka brokers are available. Thus, we are only able to connect to just a kafka leader.

## Solution
Use a YAML array of strings like this:
```yaml
alexandria:
  ...
  eventbus:
    kafka:
      brokers:
        - "kafka_leader:9090"
        - "kafka_replica_1:9090"
        - "kafka_replica_2:9090" 
```
Furthermore, split each string with the _":"_ pattern to segregate the respective port and host.
